"use client";

import { useState } from "react";
import { ChevronDown, ChevronRight, Lightbulb } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CollapsibleSection } from "@/components/collapsible-section";
import { PRSuggestionList } from "@/components/pr-suggestion-list";
import { EmptyPRState } from "@/components/empty-pr-state";
import { ActionButtonGroup } from "@/components/action-button-group";
import type { PRSuggestion } from "@/types/pr-suggestion";

interface SuggestedPRSectionProps {
  planId: string;
  suggestions: PRSuggestion[];
  onCopy: (markdown: string) => void;
}

export function SuggestedPRSection({
  planId,
  suggestions,
  onCopy,
}: SuggestedPRSectionProps) {
  const [isExpanded, setIsExpanded] = useState(true);

  const generateMarkdown = () => {
    const markdown = `## 💡 Suggested Pull Requests

${suggestions
  .map(
    (suggestion, index) => `${index + 1}. **${suggestion.title}**
   ${suggestion.description}
   
   - **Complexity:** ${suggestion.complexity}
   - **Related Issues:** ${suggestion.relatedIssues || "None"}
`
  )
  .join("\n")}

---
*Generated by AI for plan: ${planId}*`;

    return markdown;
  };

  const handleCopyToClipboard = async () => {
    const markdown = generateMarkdown();
    try {
      await navigator.clipboard.writeText(markdown);
      onCopy(markdown);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className="bg-[#161b22] border border-[#30363d] rounded-lg p-6 transition-all duration-200">
      <CollapsibleSection
        isExpanded={isExpanded}
        onToggle={() => setIsExpanded(!isExpanded)}
        header={
          <div className="flex items-center justify-between w-full">
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 bg-[#d299221a] rounded-full flex items-center justify-center">
                <Lightbulb className="w-4 h-4 text-[#d29922]" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-[#e6edf3]">
                  Suggested Pull Requests
                </h3>
              </div>
            </div>

            <div className="flex items-center space-x-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsExpanded(!isExpanded)}
                className="text-[#7d8590] hover:text-[#e6edf3] hover:bg-[#21262d] p-2"
              >
                {isExpanded ? (
                  <ChevronDown className="w-4 h-4" />
                ) : (
                  <ChevronRight className="w-4 h-4" />
                )}
              </Button>
            </div>
          </div>
        }
      >
        <div className="mt-4">
          {suggestions.length > 0 ? (
            <div className="space-y-4">
              <PRSuggestionList suggestions={suggestions} />
              {suggestions.length > 0 && (
                <ActionButtonGroup onCopy={handleCopyToClipboard} />
              )}
            </div>
          ) : (
            <EmptyPRState />
          )}
        </div>
      </CollapsibleSection>
    </div>
  );
}
